#!/bin/sh

APPDIR=$(dirname "$0")
java  -Djava.library.path="$APPDIR" -cp "$APPDIR/lib/mpeAsyncClient.jar:$APPDIR/lib/core.jar:$APPDIR/lib/mpe.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl.jar:$APPDIR/lib/opengl.jar" mpeAsyncClient
